
export const senegalRegions = [
  "Dakar", "Diourbel", "Fatick", "Kaffrine", "Kaolack", "Kédougou", 
  "Kolda", "Louga", "Matam", "Saint-Louis", "Sédhiou", "Tambacounda", 
  "Thiès", "Ziguinchor"
];

export const senegalCommunes = [
    "Bambey",
    "Diourbel",
    "Mbacké",
    "Bargny",
    "Dakar",
    "Gorée",
    "Guédiawaye",
    "Pikine",
    "Rufisque",
    "Diamniadio",
    "Sébikotane",
    "Fatick",
    "Guinguinéo",
    "Passy",
    "Sokone",
    "Foundiougne",
    "Kaffrine",
    "Koungheul",
    "Kaolack",
    "Ndoffane",
    "Kédougou",
    "Kolda",
    "Vélingara",
    "Kébémer",
    "Linguère",
    "Louga",
    "Dara",
    "Kanel",
    "Matam",
    "Ourossogui",
    "Ranérou",
    "Sémé",
    "Sinthiou Bamambé-Banadji",
    "Thilogne",
    "Agnam-Goly",
    "Dagana",
    "Podor",
    "Richard-Toll",
    "Saint-Louis",
    "Ndioum",
    "Golléré",
    "Sédhiou",
    "Bakel",
    "Goudiry",
    "Kidira",
    "Koumpentoum",
    "Makincoly",
    "Tambacounda",
    "Joal-Fadiouth",
    "Kayar",
    "Khombole",
    "Mbour",
    "Mékhé",
    "Pout",
    "Saly Portudal",
    "Thiadiaye",
    "Thiès",
    "Tivaouane",
    "Bignona",
    "Goudomp",
    "Oussouye",
    "Thionck-Essyl",
    "Ziguinchor",
    "Marsassoum",
    "Affiniam",
    "Agnack",
    "Medina Wandifa",
    "Samick",
    "Tanaff",
    "Diouloulou",
    "Kafountine",
    "Ross Béthio",
    "Gandon",
    "Mpal",
    "Rosso",
    "Dodel",
    "Gamé",
    "Démette",
    "Galoya Toucouleur",
    "Ndiayène Pendao",
    "Niandane",
    "Boké Dialloubé",
    "Mboumba",
    "Guédé Chantier",
    "Fanaye",
    "Diawara",
    "Waoundé",
    "Orkadiéré",
    "Dabia",
    "Bala",
    "Kothiary",
    "Missirah",
    "Diaobé-Kabendou",
    "Dabo",
    "Saré Yoba Diéga",
    "Salikégné",
    "Niaming",
    "Coumbacara",
    "Médina Gounass",
    "Dialacoto",
    "Nirik",
    "Koussanar",
    "Malem-Hodar",
    "Nganda",
    "Ida Mouride",
    "Gniby",
    "Gossas",
    "Ourour",
    "Colobane",
    "Mboss",
    "Mbar",
    "Darou Minam 2",
    "Touba",
    "Ndièye",
    "Nguékokh",
    "Popenguine",
    "Gandigal",
    "Ngaparou",
    "Somone",
    "Diass",
    "Sindia",
    "Malicounda",
    "Fissel",
    "Ndiaganiao",
    "Tattaguine",
    "Patar",
    "Niakhar",
    "Diofior",
    "Djilass",
    "Fimela",
    "Loul Sessène",
    "Ndangane",
    "Palmarin Facao",
    "Mar Lodj",
    "Toubacouta",
    "Karang Poste",
    "Soum",
    "Keur Madiabel",
    "Wack Ngouna",
    "Médina Sabakh",
    "Paos Koto",
    "Nioro du Rip",
    "Keur Socé",
    "Gandiaye",
    "Kahone",
    "Sibassor",
    "Latmingué",
    "Ndora",
    "Birkelane",
    "Mabo",
    "Touba Mbella",
    "Darou Mousty",
    "Koki",
    "Mbodjène",
    "Ndande",
    "Pire Goureye",
    "Thilmakha",
    "Mboro",
    "Notto",
    "Diogo",
    "Darou Khoudoss",
    "Mont-Rolland",
    "Mérina Dakhar",
    "Fandène",
    "Ngoundiane",
    "Touba Toul",
    "Nguékhokh",
    "Sandirara",
    "Tassette",
    "Keur Moussa",
    "Diender",
    "Foulpointe",
    "Yenne",
    "Sendou",
    "Sangalkam",
    "Tivaouane Peulh-Niaga",
    "Yeumbeul",
    "Thiaroye",
    "Mbao",
    "Dalifort",
    "Hann Bel-Air",
    "Dieuppeul-Derklé",
    "Fann-Point E-Amitié",
    "Médina",
    "Gueule Tapée-Fass-Colobane",
    "Grand Yoff",
    "Patte d'Oie",
    "HLM",
    "Biscuiterie",
    "Sicap-Liberté",
    "Grand Dakar",
    "Camberène",
    "Parcelles Assainies",
    "Golf Sud",
    "Sam Notaire",
    "Wakhinane Nimzatt",
    "Ndiarème Limoulaye",
    "Djidah Thiaroye Kaw",
    "Thiaroye-sur-Mer",
    "Diamaguène Sicap Mbao",
    "Mbeubeuss",
    "Keur Massar",
    "Jaxaay-Parcelles-Niakoul Rap",
    "Malika",
    "Boune",
    "Bandafassi",
    "Dindéfélo",
    "Fongolimbi",
    "Tomboronkoto",
    "Saraya",
    "Sabodala",
    "Khossanto",
    "Ndiébène Gandiol",
    "Fass Ngom",
    "Ronkh",
    "Saldé",
    "Pété",
    "Mbolo Birane",
    "Doumga Ouro Alpha",
    "Bokiladji",
    "Dendoudi",
    "Diorbivol",
    "Guédé Village",
    "Diama",
    "Diagle",
    "Sassel",
    "Dioundou",
    "Bokhol",
    "Mbane",
    "Ngnith",
    "Gaé",
    "Thillé Boubacar",
    "Aéré Lao",
    "Nabadji Civol",
    "Ogo",
    "Boké",
    "Lao",
    "Madina Ndiathbé",
    "Ndiaffate",
    "Ndiayène",
    "Mbadakhoune",
    "Dara Mboss",
    "Gagnick",
    "Panal",
    "Bandègne",
    "Boulal",
    "Mbeuleukhé",
    "Syer",
    "Thiamène",
    "Thiel",
    "Yang-Yang",
    "Barkédji",
    "Dodji",
    "Sagatta",
    "Sakassou",
    "Ndindy",
    "Kael",
    "Ndiop",
    "Taïf",
    "Sadio",
    "Diakhao",
    "Toucar",
    "Ngayokhème",
    "Niodior",
    "Djilor",
    "Mar Fafaco",
    "Keur Saloum Diané",
    "Dionewar",
    "Maka-Yop",
    "Diossong",
    "Ndramé Escale",
    "Ribot Escale",
    "Sagna",
    "Touba Ali Mbinde",
    "Mbeuleup",
    "Khelcom",
    "Diamagadio",
    "Kaymor",
    "Darou Salam Typ",
    "Lour Escale",
    "Missirah Wadene",
    "Ngathie Naoudé",
    "Fass",
    "Diarrère",
    "Ndiago",
    "Nguéniène",
    "Sandiara"
];
